[2024-07-18T12:11:02.225+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T12:11:02.230+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_a_batch_every_20_seconds.process_and_upload_to_s3 scheduled__2024-07-18T00:00:20+00:00 [queued]>
[2024-07-18T12:11:02.233+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_a_batch_every_20_seconds.process_and_upload_to_s3 scheduled__2024-07-18T00:00:20+00:00 [queued]>
[2024-07-18T12:11:02.233+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-18T12:11:02.239+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_and_upload_to_s3> on 2024-07-18 00:00:20+00:00
[2024-07-18T12:11:02.242+0530] {standard_task_runner.py:64} INFO - Started process 18371 to run task
[2024-07-18T12:11:02.244+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'upload_a_batch_every_20_seconds', 'process_and_upload_to_s3', 'scheduled__2024-07-18T00:00:20+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/car_insurance_policy_dag.py', '--cfg-path', '/tmp/tmp39r45m5z']
[2024-07-18T12:11:02.244+0530] {standard_task_runner.py:91} INFO - Job 5: Subtask process_and_upload_to_s3
[2024-07-18T12:11:02.261+0530] {task_command.py:426} INFO - Running <TaskInstance: upload_a_batch_every_20_seconds.process_and_upload_to_s3 scheduled__2024-07-18T00:00:20+00:00 [running]> on host growlt245
[2024-07-18T12:11:02.286+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='upload_a_batch_every_20_seconds' AIRFLOW_CTX_TASK_ID='process_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:00:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-18T00:00:20+00:00'
[2024-07-18T12:11:02.287+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T12:11:02.287+0530] {logging_mixin.py:188} INFO - Current working directory: /home/growlt245
[2024-07-18T12:11:02.894+0530] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'local_to_s3_bucket', switching to empty.
[2024-07-18T12:11:02.894+0530] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-07-18T12:11:05.112+0530] {car_insurance_policy_dag.py:37} ERROR - Error uploading batch 1: Unable to locate credentials
[2024-07-18T12:11:05.112+0530] {car_insurance_policy_dag.py:93} ERROR - Error in process_and_upload: Unable to locate credentials
[2024-07-18T12:11:05.112+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T12:11:05.112+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/growlt245/airflow/dags/car_insurance_policy_dag.py", line 87, in process_and_upload
    upload_to_s3(current_batch_num, batch_data, s3_hook)
  File "/home/growlt245/airflow/dags/car_insurance_policy_dag.py", line 31, in upload_to_s3
    s3_hook.load_file(temp_file, key=s3_key, bucket_name=S3_BUCKET_NAME, replace=True)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1098, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/growlt245/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 145, in upload_file
    return transfer.upload_file(
  File "/home/growlt245/.local/lib/python3.10/site-packages/boto3/s3/transfer.py", line 372, in upload_file
    future.result()
  File "/home/growlt245/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/growlt245/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/growlt245/.local/lib/python3.10/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/s3transfer/upload.py", line 764, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/client.py", line 1001, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/client.py", line 1027, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/signers.py", line 199, in sign
    auth.add_auth(request)
  File "/home/growlt245/.local/lib/python3.10/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2024-07-18T12:11:05.115+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_a_batch_every_20_seconds, task_id=process_and_upload_to_s3, run_id=scheduled__2024-07-18T00:00:20+00:00, execution_date=20240718T000020, start_date=20240718T064102, end_date=20240718T064105
[2024-07-18T12:11:05.121+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task process_and_upload_to_s3 (Unable to locate credentials; 18371)
[2024-07-18T12:11:05.146+0530] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-18T12:11:05.163+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T12:11:05.164+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
