[2024-07-19T08:56:07.648+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T08:56:07.654+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_a_batch_every_20_sec.process_and_upload_to_s3 scheduled__2024-07-19T00:01:00+00:00 [queued]>
[2024-07-19T08:56:07.656+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_a_batch_every_20_sec.process_and_upload_to_s3 scheduled__2024-07-19T00:01:00+00:00 [queued]>
[2024-07-19T08:56:07.656+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-19T08:56:07.662+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_and_upload_to_s3> on 2024-07-19 00:01:00+00:00
[2024-07-19T08:56:07.665+0530] {standard_task_runner.py:64} INFO - Started process 155113 to run task
[2024-07-19T08:56:07.667+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'upload_a_batch_every_20_sec', 'process_and_upload_to_s3', 'scheduled__2024-07-19T00:01:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/car_insurance_policy_dag.py', '--cfg-path', '/tmp/tmpbksxpz7f']
[2024-07-19T08:56:07.667+0530] {standard_task_runner.py:91} INFO - Job 101: Subtask process_and_upload_to_s3
[2024-07-19T08:56:07.684+0530] {task_command.py:426} INFO - Running <TaskInstance: upload_a_batch_every_20_sec.process_and_upload_to_s3 scheduled__2024-07-19T00:01:00+00:00 [running]> on host growlt245
[2024-07-19T08:56:07.710+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='upload_a_batch_every_20_sec' AIRFLOW_CTX_TASK_ID='process_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-19T00:01:00+00:00'
[2024-07-19T08:56:07.710+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T08:56:07.711+0530] {logging_mixin.py:188} INFO - Current working directory: /home/growlt245
[2024-07-19T08:56:07.711+0530] {car_insurance_policy_dag.py:94} ERROR - Error in process_and_upload: [Errno 2] No such file or directory: '/home/growlt245/airflow/Amended_Insurance_Product_Purchase_dataset.csv'
[2024-07-19T08:56:07.711+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T08:56:07.711+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/growlt245/airflow/dags/car_insurance_policy_dag.py", line 47, in process_and_upload
    df = pd.read_csv(LOCAL_CSV_FILE)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1024, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 618, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1618, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1878, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/growlt245/airflow/Amended_Insurance_Product_Purchase_dataset.csv'
[2024-07-19T08:56:07.714+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_a_batch_every_20_sec, task_id=process_and_upload_to_s3, run_id=scheduled__2024-07-19T00:01:00+00:00, execution_date=20240719T000100, start_date=20240719T032607, end_date=20240719T032607
[2024-07-19T08:56:07.719+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 101 for task process_and_upload_to_s3 ([Errno 2] No such file or directory: '/home/growlt245/airflow/Amended_Insurance_Product_Purchase_dataset.csv'; 155113)
[2024-07-19T08:56:07.759+0530] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-19T08:56:07.776+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T08:56:07.776+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
