[2024-07-19T09:07:20.555+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T09:07:20.561+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_a_batch_every_20_sec.process_and_upload_to_s3 scheduled__2024-07-19T00:18:20+00:00 [queued]>
[2024-07-19T09:07:20.564+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_a_batch_every_20_sec.process_and_upload_to_s3 scheduled__2024-07-19T00:18:20+00:00 [queued]>
[2024-07-19T09:07:20.564+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-19T09:07:20.569+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_and_upload_to_s3> on 2024-07-19 00:18:20+00:00
[2024-07-19T09:07:20.575+0530] {standard_task_runner.py:64} INFO - Started process 160251 to run task
[2024-07-19T09:07:20.576+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'upload_a_batch_every_20_sec', 'process_and_upload_to_s3', 'scheduled__2024-07-19T00:18:20+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/car_insurance_policy_dag.py', '--cfg-path', '/tmp/tmpnzycm__n']
[2024-07-19T09:07:20.577+0530] {standard_task_runner.py:91} INFO - Job 310: Subtask process_and_upload_to_s3
[2024-07-19T09:07:20.594+0530] {task_command.py:426} INFO - Running <TaskInstance: upload_a_batch_every_20_sec.process_and_upload_to_s3 scheduled__2024-07-19T00:18:20+00:00 [running]> on host growlt245
[2024-07-19T09:07:20.621+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='upload_a_batch_every_20_sec' AIRFLOW_CTX_TASK_ID='process_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T00:18:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-19T00:18:20+00:00'
[2024-07-19T09:07:20.622+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T09:07:20.622+0530] {logging_mixin.py:188} INFO - Current working directory: /home/growlt245
[2024-07-19T09:07:21.609+0530] {base.py:84} INFO - Using connection ID 'local_to_s3' for task execution.
[2024-07-19T09:07:21.610+0530] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='local_to_s3', conn_type='aws') credentials retrieved from login and password.
[2024-07-19T09:07:21.849+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-19T09:07:21.859+0530] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 160251. PIDs of all processes in the group: [160251]
[2024-07-19T09:07:21.859+0530] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 160251
[2024-07-19T09:07:21.860+0530] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-19T09:07:22.261+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T09:07:22.267+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/growlt245/airflow/dags/car_insurance_policy_dag.py", line 88, in process_and_upload
    upload_to_s3(current_batch_num, batch_data, s3_hook)
  File "/home/growlt245/airflow/dags/car_insurance_policy_dag.py", line 32, in upload_to_s3
    s3_hook.load_file(temp_file, key=s3_key, bucket_name=S3_BUCKET_NAME, replace=True)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1098, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/growlt245/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 145, in upload_file
    return transfer.upload_file(
  File "/home/growlt245/.local/lib/python3.10/site-packages/boto3/s3/transfer.py", line 372, in upload_file
    future.result()
  File "/home/growlt245/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/growlt245/.local/lib/python3.10/site-packages/s3transfer/futures.py", line 261, in result
    self._done_event.wait(MAXINT)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
  File "/home/growlt245/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-19T09:07:22.270+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_a_batch_every_20_sec, task_id=process_and_upload_to_s3, run_id=scheduled__2024-07-19T00:18:20+00:00, execution_date=20240719T001820, start_date=20240719T033720, end_date=20240719T033722
[2024-07-19T09:07:22.314+0530] {process_utils.py:80} INFO - Process psutil.Process(pid=160251, status='terminated', exitcode=2, started='09:07:20') (160251) terminated with exit code 2
